### ISSUE TITLE
Make the introduction screen visible only once per user(One-time intro only).

### ISSUE THREAD

**Issue by nexi9** [CareerDevelopmentHub/Bill-Splitter#5]
Hint: There's a specific widget for this to work. No need to store user data.
However, if you want to use database you can.

**Comment by ampatro4** [comment]
I am interested to work on this task 
can u assign this to me???

**Comment by nexi9** [comment]
@ampatro4 Sure!

**Comment by Perumallpardhiv** [comment]
@nexi9 
I will also try this pls assign

**Comment by Perumallpardhiv** [comment]
@nexi9 
Pls check #11 which fixes : #5
